# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # 🔥 بررسی بروزرسانی‌های PHP (Composer)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "SajjadAkbari"
    assignees:
      - "SajjadAkbari"
    labels:
      - "dependencies"
      - "security"
      - "php"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "phpunit/phpunit"
        versions: ["<10.0"]
    commit-message:
      prefix: "composer update:"
      include: "scope"
    target-branch: "develop"
    milestone: "v1.0.0"
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    insecure-external-code-execution: "deny"

  # 🚀 بررسی بروزرسانی‌های JavaScript (NPM/Yarn)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "SajjadAkbari"
    assignees:
      - "SajjadAkbari"
    labels:
      - "dependencies"
      - "security"
      - "javascript"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "webpack"
        versions: ["<5.0"]
    commit-message:
      prefix: "npm update:"
      include: "scope"
    groups:
      test-dependencies:
        patterns:
          - "jest/*"
          - "mocha/*"

  # 🛠️ بررسی بروزرسانی‌های GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "github-actions"
      - "ci/cd"
    commit-message:
      prefix: "ci update:"
      include: "scope"
    security-updates:
      enabled: true

  # 🏗️ بررسی بروزرسانی‌های Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "UTC"
    labels:
      - "docker"
    commit-message:
      prefix: "docker update:"
      include: "scope"

  # 🔧 بررسی بروزرسانی‌های RubyGems (برای CI/CD)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "ruby"
    commit-message:
      prefix: "bundler update:"
      include: "scope"

  # 🐍 بررسی بروزرسانی‌های Python (برای توسعه و تست)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "UTC"
    labels:
      - "python"
      - "dependencies"
    commit-message:
      prefix: "pip update:"
      include: "scope"
